package routers

import (
	"notepad-api/controllers"

	"github.com/astaxie/beego"
	//	"github.com/astaxie/beego/context"
)

func init() {
	ns := beego.NewNamespace("/API",
		beego.NSNamespace("/V2.0",
			beego.NSNamespace("/Note",
				beego.NSRouter("/Update", &controllers.NoteController{}, "*:UpdateByV2"),
				beego.NSRouter("/Delete", &controllers.NoteController{}, "*:DeleteByV2"),
			),
		),
		beego.NSNamespace("/V1.0",
			beego.NSNamespace("/Attachment",
				beego.NSRouter("/Upload", &controllers.AttachmentController{}, "*:Upload"),
				beego.NSRouter("/Add", &controllers.AttachmentController{}, "*:Add"),
				beego.NSRouter("/AddPublic", &controllers.AttachmentController{}, "*:AddPublic"),
				beego.NSRouter("/CheckAttach", &controllers.AttachmentController{}, "*:Check"),
				beego.NSRouter("/DownLoad", &controllers.AttachmentController{}, "*:DownLoad"),
			),
			beego.NSNamespace("/Category",
				beego.NSRouter("/All", &controllers.CategoryController{}, "*:All"),
				beego.NSRouter("/WebAll", &controllers.CategoryController{}, "*:WebAll"),
				beego.NSRouter("/Search", &controllers.CategoryController{}, "*:Search"),
				beego.NSRouter("/Remove", &controllers.CategoryController{}, "*:RemoveCategory"),
				beego.NSRouter("/Recover", &controllers.CategoryController{}, "*:RecoverCategory"),
				beego.NSRouter("/NoteList", &controllers.CategoryController{}, "*:NoteList"),
				beego.NSRouter("/NoteDeletedList", &controllers.CategoryController{}, "*:NoteDeletedList"),
				beego.NSRouter("/AllDeleted", &controllers.CategoryController{}, "*:AllDelete"),
				beego.NSRouter("/Create", &controllers.CategoryController{}, "*:Create"),
				beego.NSRouter("/Update", &controllers.CategoryController{}, "*:Update"),
				beego.NSRouter("/Delete", &controllers.CategoryController{}, "*:Delete"),
				beego.NSRouter("/DeleteAll", &controllers.CategoryController{}, "*:DeleteAll"),
			),

			beego.NSNamespace("/Note",
				beego.NSRouter("/GetNoteID", &controllers.NoteController{}, "*:GetNoteID"),
				beego.NSRouter("/Recover", &controllers.NoteController{}, "*:RecoverNote"),
				beego.NSRouter("/Remove", &controllers.NoteController{}, "*:RemoveNote"),
				beego.NSRouter("/NoCategory", &controllers.NoteController{}, "*:NoCategory"),
				beego.NSRouter("/All", &controllers.NoteController{}, "*:AllNote"),
				//				beego.NSRouter("/GetByUsn", &controllers.NoteController{}, "*:GetByUsn"),
				beego.NSRouter("/Get", &controllers.NoteController{}, "*:GetNote"),
				beego.NSRouter("/GetDeleted", &controllers.NoteController{}, "*:GetNoteDeleted"),
				beego.NSRouter("/Move", &controllers.NoteController{}, "*:Move"),
				beego.NSRouter("/Create", &controllers.NoteController{}, "*:Create"),
				beego.NSRouter("/Update", &controllers.NoteController{}, "*:Update"),
				beego.NSRouter("/Delete", &controllers.NoteController{}, "*:Delete"),
				beego.NSRouter("/DeleteAttach", &controllers.NoteController{}, "*:DeleteAttach"),
			),
			beego.NSNamespace("/Template",
				beego.NSRouter("/TemplateList", &controllers.TemplateController{}, "*:TemplateList"),
				beego.NSRouter("/TemplateAdd", &controllers.TemplateController{}, "*:AddTemplate"),
				beego.NSRouter("/TemplateUpdate", &controllers.TemplateController{}, "*:UpdateTemplate"),
				beego.NSRouter("/TemplateDelete", &controllers.TemplateController{}, "*:DeleteTemplate"),
			),
			beego.NSNamespace("/Paper",
				beego.NSRouter("/PaperList", &controllers.PaperController{}, "*:Paperlist"),
				beego.NSRouter("/PaperAdd", &controllers.PaperController{}, "*:AddPaper"),
				beego.NSRouter("/PaperUpdate", &controllers.PaperController{}, "*:UpdatePaper"),
				beego.NSRouter("/PaperDelete", &controllers.PaperController{}, "*:DeletePaper"),
			),
			beego.NSNamespace("/Widget",
				beego.NSRouter("/WidgetList", &controllers.WidgetController{}, "*:Widgetlist"),
				beego.NSRouter("/WidgetAdd", &controllers.WidgetController{}, "*:AddWidget"),
				beego.NSRouter("/WidgetUpdate", &controllers.WidgetController{}, "*:UpdateWidget"),
				beego.NSRouter("/WidgetDelete", &controllers.WidgetController{}, "*:DeleteWidget"),
			),
			beego.NSNamespace("/Share",
				beego.NSRouter("/Publish", &controllers.ShareController{}, "*:Publish"),
				beego.NSRouter("/GetShareMessage", &controllers.ShareController{}, "*:GetShareMessage"),
				beego.NSRouter("/Show", &controllers.ShareController{}, "*:Show"),
				beego.NSRouter("/GetShare", &controllers.ShareController{}, "*:GetShare"),
				beego.NSRouter("/CancelShare", &controllers.ShareController{}, "*:CancleShare"),
				beego.NSRouter("/GetQuestion", &controllers.ShareController{}, "*:GetQuestion"),
			),
			beego.NSNamespace("/Cloud",
				beego.NSRouter("/GetUploadToken", &controllers.CloudBoxController{}, "*:GetUploadToken"),
				beego.NSRouter("/GetUploadTokenWithCB", &controllers.CloudBoxController{}, "*:GetUploadTokenWithCB"),
				beego.NSRouter("/CallBack", &controllers.CloudBoxController{}, "*:CallBack"),
				beego.NSRouter("/GetDownloadURL", &controllers.CloudBoxController{}, "*:GetDownloadURL"),
			),
			beego.NSNamespace("/User",
				beego.NSRouter("/GetToken", &controllers.UserController{}, "*:GetToken"),
				beego.NSRouter("/AppGetToken", &controllers.UserController{}, "*:AppGetToken"),
				beego.NSRouter("/AllTrash", &controllers.UserController{}, "*:AllTrash"),
				beego.NSRouter("/GetUserInfo", &controllers.UserController{}, "*:GetUserInfo"),
				beego.NSRouter("/LoginOut", &controllers.UserController{}, "*:LoginOut"),
				beego.NSRouter("/Cancellation", &controllers.UserController{}, "*:Cancellation"),
			),
			beego.NSNamespace("/Sync",
				beego.NSRouter("/GetUserUsn", &controllers.SynchController{}, "*:GetUserUsn"),
				beego.NSRouter("/GetSyncNotes", &controllers.SynchController{}, "*:GetSyncNotes"),
				beego.NSRouter("/GetSyncCategorys", &controllers.SynchController{}, "*:GetSyncCategorys"),
			),
			beego.NSNamespace("/Vote",
				beego.NSRouter("/VoteAdd", &controllers.VoteController{}, "*:VoteAdd"),
				beego.NSRouter("/VoteUpdate", &controllers.VoteController{}, "*:VoteUpdate"),
				beego.NSRouter("/VoteGet", &controllers.VoteController{}, "*:VoteGet"),
				beego.NSRouter("/VoteGetByNote", &controllers.VoteController{}, "*:VoteGetByNote"),
				beego.NSRouter("/CancelVote", &controllers.VoteController{}, "*:CancleVote"),
				beego.NSRouter("/ClickVote", &controllers.VoteController{}, "*:ClickVote"),
			),
		),
	)
	beego.AddNamespace(ns)
	//拦截：验证登录

}
